package org.example.xhc.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_coupon
 */
/**
* Created by Mybatis Generator on 2022/12/10
*/
@Data
public class Coupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   优惠券类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   使用平台：0->全部；1->移动；2->PC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.platform
     *
     * @mbg.generated
     */
    private Integer platform;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   每人限领张数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.per_limit
     *
     * @mbg.generated
     */
    private Integer perLimit;

    /**
     * Database Column Remarks:
     *   使用门槛；0表示无门槛
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.min_point
     *
     * @mbg.generated
     */
    private BigDecimal minPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     * Database Column Remarks:
     *   使用类型：0->全场通用；1->指定分类；2->指定商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.use_type
     *
     * @mbg.generated
     */
    private Integer useType;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * Database Column Remarks:
     *   发行数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.publish_count
     *
     * @mbg.generated
     */
    private Integer publishCount;

    /**
     * Database Column Remarks:
     *   已使用数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.use_count
     *
     * @mbg.generated
     */
    private Integer useCount;

    /**
     * Database Column Remarks:
     *   领取数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.receive_count
     *
     * @mbg.generated
     */
    private Integer receiveCount;

    /**
     * Database Column Remarks:
     *   可以领取的日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.enable_time
     *
     * @mbg.generated
     */
    private LocalDateTime enableTime;

    /**
     * Database Column Remarks:
     *   优惠码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   可领取的会员类型：0->无限时
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon.member_level
     *
     * @mbg.generated
     */
    private Integer memberLevel;
}