package org.example.xhc.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oms_order
 */
public class Order {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     * Database Column Remarks:
     *   订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     * Database Column Remarks:
     *   提交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     * Database Column Remarks:
     *   用户帐号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_username
     *
     * @mbg.generated
     */
    private String memberUsername;

    /**
     * Database Column Remarks:
     *   订单总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     * Database Column Remarks:
     *   应付金额（实际支付金额）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal payAmount;

    /**
     * Database Column Remarks:
     *   运费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.freight_amount
     *
     * @mbg.generated
     */
    private BigDecimal freightAmount;

    /**
     * Database Column Remarks:
     *   促销优化金额（促销价、满减、阶梯价）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_amount
     *
     * @mbg.generated
     */
    private BigDecimal promotionAmount;

    /**
     * Database Column Remarks:
     *   积分抵扣金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration_amount
     *
     * @mbg.generated
     */
    private BigDecimal integrationAmount;

    /**
     * Database Column Remarks:
     *   优惠券抵扣金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_amount
     *
     * @mbg.generated
     */
    private BigDecimal couponAmount;

    /**
     * Database Column Remarks:
     *   管理员后台调整订单使用的折扣金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.discount_amount
     *
     * @mbg.generated
     */
    private BigDecimal discountAmount;

    /**
     * Database Column Remarks:
     *   支付方式：0->未支付；1->支付宝；2->微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     * Database Column Remarks:
     *   订单来源：0->PC订单；1->app订单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.source_type
     *
     * @mbg.generated
     */
    private Integer sourceType;

    /**
     * Database Column Remarks:
     *   订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   订单类型：0->正常订单；1->秒杀订单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     * Database Column Remarks:
     *   物流公司(配送方式)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_company
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     * Database Column Remarks:
     *   物流单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_sn
     *
     * @mbg.generated
     */
    private String deliverySn;

    /**
     * Database Column Remarks:
     *   自动确认时间（天）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.auto_confirm_day
     *
     * @mbg.generated
     */
    private Integer autoConfirmDay;

    /**
     * Database Column Remarks:
     *   可以获得的积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration
     *
     * @mbg.generated
     */
    private Integer integration;

    /**
     * Database Column Remarks:
     *   可以活动的成长值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.growth
     *
     * @mbg.generated
     */
    private Integer growth;

    /**
     * Database Column Remarks:
     *   活动信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_info
     *
     * @mbg.generated
     */
    private String promotionInfo;

    /**
     * Database Column Remarks:
     *   发票类型：0->不开发票；1->电子发票；2->纸质发票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_type
     *
     * @mbg.generated
     */
    private Integer billType;

    /**
     * Database Column Remarks:
     *   发票抬头
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_header
     *
     * @mbg.generated
     */
    private String billHeader;

    /**
     * Database Column Remarks:
     *   发票内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_content
     *
     * @mbg.generated
     */
    private String billContent;

    /**
     * Database Column Remarks:
     *   收票人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_phone
     *
     * @mbg.generated
     */
    private String billReceiverPhone;

    /**
     * Database Column Remarks:
     *   收票人邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_email
     *
     * @mbg.generated
     */
    private String billReceiverEmail;

    /**
     * Database Column Remarks:
     *   收货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_name
     *
     * @mbg.generated
     */
    private String rcvName;

    /**
     * Database Column Remarks:
     *   收货人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_phone
     *
     * @mbg.generated
     */
    private String rcvPhone;

    /**
     * Database Column Remarks:
     *   收货人邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_post_code
     *
     * @mbg.generated
     */
    private String rcvPostCode;

    /**
     * Database Column Remarks:
     *   省份/直辖市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_province
     *
     * @mbg.generated
     */
    private String rcvProvince;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_city
     *
     * @mbg.generated
     */
    private String rcvCity;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_region
     *
     * @mbg.generated
     */
    private String rcvRegion;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_detail_address
     *
     * @mbg.generated
     */
    private String rcvDetailAddress;

    /**
     * Database Column Remarks:
     *   订单备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * Database Column Remarks:
     *   确认收货状态：0->未确认；1->已确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.confirm_status
     *
     * @mbg.generated
     */
    private Integer confirmStatus;

    /**
     * Database Column Remarks:
     *   删除状态：0->未删除；1->已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delete_status
     *
     * @mbg.generated
     */
    private Integer deleteStatus;

    /**
     * Database Column Remarks:
     *   下单时使用的积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.use_integration
     *
     * @mbg.generated
     */
    private Integer useIntegration;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.payment_time
     *
     * @mbg.generated
     */
    private LocalDateTime paymentTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_time
     *
     * @mbg.generated
     */
    private LocalDateTime deliveryTime;

    /**
     * Database Column Remarks:
     *   确认收货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receive_time
     *
     * @mbg.generated
     */
    private LocalDateTime receiveTime;

    /**
     * Database Column Remarks:
     *   评价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.comment_time
     *
     * @mbg.generated
     */
    private LocalDateTime commentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.id
     *
     * @return the value of oms_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.id
     *
     * @param id the value for oms_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.member_id
     *
     * @return the value of oms_order.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.member_id
     *
     * @param memberId the value for oms_order.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.coupon_id
     *
     * @return the value of oms_order.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.coupon_id
     *
     * @param couponId the value for oms_order.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_sn
     *
     * @return the value of oms_order.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_sn
     *
     * @param orderSn the value for oms_order.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.create_time
     *
     * @return the value of oms_order.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.create_time
     *
     * @param createDate the value for oms_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.member_username
     *
     * @return the value of oms_order.member_username
     *
     * @mbg.generated
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.member_username
     *
     * @param memberUsername the value for oms_order.member_username
     *
     * @mbg.generated
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername == null ? null : memberUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.total_amount
     *
     * @return the value of oms_order.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.total_amount
     *
     * @param totalAmount the value for oms_order.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_amount
     *
     * @return the value of oms_order.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_amount
     *
     * @param payAmount the value for oms_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.freight_amount
     *
     * @return the value of oms_order.freight_amount
     *
     * @mbg.generated
     */
    public BigDecimal getFreightAmount() {
        return freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.freight_amount
     *
     * @param freightAmount the value for oms_order.freight_amount
     *
     * @mbg.generated
     */
    public void setFreightAmount(BigDecimal freightAmount) {
        this.freightAmount = freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.promotion_amount
     *
     * @return the value of oms_order.promotion_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPromotionAmount() {
        return promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.promotion_amount
     *
     * @param promotionAmount the value for oms_order.promotion_amount
     *
     * @mbg.generated
     */
    public void setPromotionAmount(BigDecimal promotionAmount) {
        this.promotionAmount = promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.integration_amount
     *
     * @return the value of oms_order.integration_amount
     *
     * @mbg.generated
     */
    public BigDecimal getIntegrationAmount() {
        return integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.integration_amount
     *
     * @param integrationAmount the value for oms_order.integration_amount
     *
     * @mbg.generated
     */
    public void setIntegrationAmount(BigDecimal integrationAmount) {
        this.integrationAmount = integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.coupon_amount
     *
     * @return the value of oms_order.coupon_amount
     *
     * @mbg.generated
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.coupon_amount
     *
     * @param couponAmount the value for oms_order.coupon_amount
     *
     * @mbg.generated
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.discount_amount
     *
     * @return the value of oms_order.discount_amount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.discount_amount
     *
     * @param discountAmount the value for oms_order.discount_amount
     *
     * @mbg.generated
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_type
     *
     * @return the value of oms_order.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_type
     *
     * @param payType the value for oms_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.source_type
     *
     * @return the value of oms_order.source_type
     *
     * @mbg.generated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.source_type
     *
     * @param sourceType the value for oms_order.source_type
     *
     * @mbg.generated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.status
     *
     * @return the value of oms_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.status
     *
     * @param status the value for oms_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_type
     *
     * @return the value of oms_order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_type
     *
     * @param orderType the value for oms_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_company
     *
     * @return the value of oms_order.delivery_company
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_company
     *
     * @param deliveryCompany the value for oms_order.delivery_company
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_sn
     *
     * @return the value of oms_order.delivery_sn
     *
     * @mbg.generated
     */
    public String getDeliverySn() {
        return deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_sn
     *
     * @param deliverySn the value for oms_order.delivery_sn
     *
     * @mbg.generated
     */
    public void setDeliverySn(String deliverySn) {
        this.deliverySn = deliverySn == null ? null : deliverySn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.auto_confirm_day
     *
     * @return the value of oms_order.auto_confirm_day
     *
     * @mbg.generated
     */
    public Integer getAutoConfirmDay() {
        return autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.auto_confirm_day
     *
     * @param autoConfirmDay the value for oms_order.auto_confirm_day
     *
     * @mbg.generated
     */
    public void setAutoConfirmDay(Integer autoConfirmDay) {
        this.autoConfirmDay = autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.integration
     *
     * @return the value of oms_order.integration
     *
     * @mbg.generated
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.integration
     *
     * @param integration the value for oms_order.integration
     *
     * @mbg.generated
     */
    public void setIntegration(Integer integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.growth
     *
     * @return the value of oms_order.growth
     *
     * @mbg.generated
     */
    public Integer getGrowth() {
        return growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.growth
     *
     * @param growth the value for oms_order.growth
     *
     * @mbg.generated
     */
    public void setGrowth(Integer growth) {
        this.growth = growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.promotion_info
     *
     * @return the value of oms_order.promotion_info
     *
     * @mbg.generated
     */
    public String getPromotionInfo() {
        return promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.promotion_info
     *
     * @param promotionInfo the value for oms_order.promotion_info
     *
     * @mbg.generated
     */
    public void setPromotionInfo(String promotionInfo) {
        this.promotionInfo = promotionInfo == null ? null : promotionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_type
     *
     * @return the value of oms_order.bill_type
     *
     * @mbg.generated
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_type
     *
     * @param billType the value for oms_order.bill_type
     *
     * @mbg.generated
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_header
     *
     * @return the value of oms_order.bill_header
     *
     * @mbg.generated
     */
    public String getBillHeader() {
        return billHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_header
     *
     * @param billHeader the value for oms_order.bill_header
     *
     * @mbg.generated
     */
    public void setBillHeader(String billHeader) {
        this.billHeader = billHeader == null ? null : billHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_content
     *
     * @return the value of oms_order.bill_content
     *
     * @mbg.generated
     */
    public String getBillContent() {
        return billContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_content
     *
     * @param billContent the value for oms_order.bill_content
     *
     * @mbg.generated
     */
    public void setBillContent(String billContent) {
        this.billContent = billContent == null ? null : billContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_receiver_phone
     *
     * @return the value of oms_order.bill_receiver_phone
     *
     * @mbg.generated
     */
    public String getBillReceiverPhone() {
        return billReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_receiver_phone
     *
     * @param billReceiverPhone the value for oms_order.bill_receiver_phone
     *
     * @mbg.generated
     */
    public void setBillReceiverPhone(String billReceiverPhone) {
        this.billReceiverPhone = billReceiverPhone == null ? null : billReceiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_receiver_email
     *
     * @return the value of oms_order.bill_receiver_email
     *
     * @mbg.generated
     */
    public String getBillReceiverEmail() {
        return billReceiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_receiver_email
     *
     * @param billReceiverEmail the value for oms_order.bill_receiver_email
     *
     * @mbg.generated
     */
    public void setBillReceiverEmail(String billReceiverEmail) {
        this.billReceiverEmail = billReceiverEmail == null ? null : billReceiverEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_name
     *
     * @return the value of oms_order.receiver_name
     *
     * @mbg.generated
     */
    public String getRcvName() {
        return rcvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_name
     *
     * @param rcvName the value for oms_order.receiver_name
     *
     * @mbg.generated
     */
    public void setRcvName(String rcvName) {
        this.rcvName = rcvName == null ? null : rcvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_phone
     *
     * @return the value of oms_order.receiver_phone
     *
     * @mbg.generated
     */
    public String getRcvPhone() {
        return rcvPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_phone
     *
     * @param rcvPhone the value for oms_order.receiver_phone
     *
     * @mbg.generated
     */
    public void setRcvPhone(String rcvPhone) {
        this.rcvPhone = rcvPhone == null ? null : rcvPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_post_code
     *
     * @return the value of oms_order.receiver_post_code
     *
     * @mbg.generated
     */
    public String getRcvPostCode() {
        return rcvPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_post_code
     *
     * @param rcvPostCode the value for oms_order.receiver_post_code
     *
     * @mbg.generated
     */
    public void setRcvPostCode(String rcvPostCode) {
        this.rcvPostCode = rcvPostCode == null ? null : rcvPostCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_province
     *
     * @return the value of oms_order.receiver_province
     *
     * @mbg.generated
     */
    public String getRcvProvince() {
        return rcvProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_province
     *
     * @param rcvProvince the value for oms_order.receiver_province
     *
     * @mbg.generated
     */
    public void setRcvProvince(String rcvProvince) {
        this.rcvProvince = rcvProvince == null ? null : rcvProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_city
     *
     * @return the value of oms_order.receiver_city
     *
     * @mbg.generated
     */
    public String getRcvCity() {
        return rcvCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_city
     *
     * @param rcvCity the value for oms_order.receiver_city
     *
     * @mbg.generated
     */
    public void setRcvCity(String rcvCity) {
        this.rcvCity = rcvCity == null ? null : rcvCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_region
     *
     * @return the value of oms_order.receiver_region
     *
     * @mbg.generated
     */
    public String getRcvRegion() {
        return rcvRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_region
     *
     * @param rcvRegion the value for oms_order.receiver_region
     *
     * @mbg.generated
     */
    public void setRcvRegion(String rcvRegion) {
        this.rcvRegion = rcvRegion == null ? null : rcvRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_detail_address
     *
     * @return the value of oms_order.receiver_detail_address
     *
     * @mbg.generated
     */
    public String getRcvDetailAddress() {
        return rcvDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_detail_address
     *
     * @param rcvDetailAddress the value for oms_order.receiver_detail_address
     *
     * @mbg.generated
     */
    public void setRcvDetailAddress(String rcvDetailAddress) {
        this.rcvDetailAddress = rcvDetailAddress == null ? null : rcvDetailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.note
     *
     * @return the value of oms_order.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.note
     *
     * @param note the value for oms_order.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.confirm_status
     *
     * @return the value of oms_order.confirm_status
     *
     * @mbg.generated
     */
    public Integer getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.confirm_status
     *
     * @param confirmStatus the value for oms_order.confirm_status
     *
     * @mbg.generated
     */
    public void setConfirmStatus(Integer confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delete_status
     *
     * @return the value of oms_order.delete_status
     *
     * @mbg.generated
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delete_status
     *
     * @param deleteStatus the value for oms_order.delete_status
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.use_integration
     *
     * @return the value of oms_order.use_integration
     *
     * @mbg.generated
     */
    public Integer getUseIntegration() {
        return useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.use_integration
     *
     * @param useIntegration the value for oms_order.use_integration
     *
     * @mbg.generated
     */
    public void setUseIntegration(Integer useIntegration) {
        this.useIntegration = useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.payment_time
     *
     * @return the value of oms_order.payment_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.payment_time
     *
     * @param paymentTime the value for oms_order.payment_time
     *
     * @mbg.generated
     */
    public void setPaymentTime(LocalDateTime paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_time
     *
     * @return the value of oms_order.delivery_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_time
     *
     * @param deliveryTime the value for oms_order.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(LocalDateTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receive_time
     *
     * @return the value of oms_order.receive_time
     *
     * @mbg.generated
     */
    public LocalDateTime getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receive_time
     *
     * @param receiveTime the value for oms_order.receive_time
     *
     * @mbg.generated
     */
    public void setReceiveTime(LocalDateTime receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.comment_time
     *
     * @return the value of oms_order.comment_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.comment_time
     *
     * @param commentTime the value for oms_order.comment_time
     *
     * @mbg.generated
     */
    public void setCommentTime(LocalDateTime commentTime) {
        this.commentTime = commentTime;
    }
}