package org.example.xhc.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_subject
 */
/**
* Created by Mybatis Generator on 2022/12/10
*/
@Data
public class subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   专题主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     * Database Column Remarks:
     *   关联产品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.product_count
     *
     * @mbg.generated
     */
    private Integer productCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.recommend_status
     *
     * @mbg.generated
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.collect_count
     *
     * @mbg.generated
     */
    private Integer collectCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.read_count
     *
     * @mbg.generated
     */
    private Integer readCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.comment_count
     *
     * @mbg.generated
     */
    private Integer commentCnt;

    /**
     * Database Column Remarks:
     *   画册图片用逗号分割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.album_pics
     *
     * @mbg.generated
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   显示状态：0->不显示；1->显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.show_status
     *
     * @mbg.generated
     */
    private Integer showStatus;

    /**
     * Database Column Remarks:
     *   转发数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.forward_count
     *
     * @mbg.generated
     */
    private Integer forwardCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.content
     *
     * @mbg.generated
     */
    private String content;
}