package org.example.xhc.entity;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_subject
 */
public class subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   专题主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     * Database Column Remarks:
     *   关联产品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.product_count
     *
     * @mbg.generated
     */
    private Integer productCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.recommend_status
     *
     * @mbg.generated
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.collect_count
     *
     * @mbg.generated
     */
    private Integer collectCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.read_count
     *
     * @mbg.generated
     */
    private Integer readCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.comment_count
     *
     * @mbg.generated
     */
    private Integer commentCnt;

    /**
     * Database Column Remarks:
     *   画册图片用逗号分割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.album_pics
     *
     * @mbg.generated
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   显示状态：0->不显示；1->显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.show_status
     *
     * @mbg.generated
     */
    private Integer showStatus;

    /**
     * Database Column Remarks:
     *   转发数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.forward_count
     *
     * @mbg.generated
     */
    private Integer forwardCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.id
     *
     * @return the value of cms_subject.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.id
     *
     * @param id the value for cms_subject.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.category_id
     *
     * @return the value of cms_subject.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.category_id
     *
     * @param categoryId the value for cms_subject.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.title
     *
     * @return the value of cms_subject.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.title
     *
     * @param title the value for cms_subject.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.pic
     *
     * @return the value of cms_subject.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.pic
     *
     * @param pic the value for cms_subject.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.product_count
     *
     * @return the value of cms_subject.product_count
     *
     * @mbg.generated
     */
    public Integer getProductCnt() {
        return productCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.product_count
     *
     * @param productCnt the value for cms_subject.product_count
     *
     * @mbg.generated
     */
    public void setProductCnt(Integer productCnt) {
        this.productCnt = productCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.recommend_status
     *
     * @return the value of cms_subject.recommend_status
     *
     * @mbg.generated
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.recommend_status
     *
     * @param recommendStatus the value for cms_subject.recommend_status
     *
     * @mbg.generated
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.create_time
     *
     * @return the value of cms_subject.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.create_time
     *
     * @param createTime the value for cms_subject.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.collect_count
     *
     * @return the value of cms_subject.collect_count
     *
     * @mbg.generated
     */
    public Integer getCollectCnt() {
        return collectCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.collect_count
     *
     * @param collectCnt the value for cms_subject.collect_count
     *
     * @mbg.generated
     */
    public void setCollectCnt(Integer collectCnt) {
        this.collectCnt = collectCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.read_count
     *
     * @return the value of cms_subject.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCnt() {
        return readCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.read_count
     *
     * @param readCnt the value for cms_subject.read_count
     *
     * @mbg.generated
     */
    public void setReadCnt(Integer readCnt) {
        this.readCnt = readCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.comment_count
     *
     * @return the value of cms_subject.comment_count
     *
     * @mbg.generated
     */
    public Integer getCommentCnt() {
        return commentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.comment_count
     *
     * @param commentCnt the value for cms_subject.comment_count
     *
     * @mbg.generated
     */
    public void setCommentCnt(Integer commentCnt) {
        this.commentCnt = commentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.album_pics
     *
     * @return the value of cms_subject.album_pics
     *
     * @mbg.generated
     */
    public String getAlbumPics() {
        return albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.album_pics
     *
     * @param albumPics the value for cms_subject.album_pics
     *
     * @mbg.generated
     */
    public void setAlbumPics(String albumPics) {
        this.albumPics = albumPics == null ? null : albumPics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.description
     *
     * @return the value of cms_subject.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.description
     *
     * @param description the value for cms_subject.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.show_status
     *
     * @return the value of cms_subject.show_status
     *
     * @mbg.generated
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.show_status
     *
     * @param showStatus the value for cms_subject.show_status
     *
     * @mbg.generated
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.forward_count
     *
     * @return the value of cms_subject.forward_count
     *
     * @mbg.generated
     */
    public Integer getForwardCnt() {
        return forwardCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.forward_count
     *
     * @param forwardCnt the value for cms_subject.forward_count
     *
     * @mbg.generated
     */
    public void setForwardCnt(Integer forwardCnt) {
        this.forwardCnt = forwardCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.content
     *
     * @return the value of cms_subject.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.content
     *
     * @param content the value for cms_subject.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}